---
misc:
  #' The beta part of the F score. 
  #' 0.5 means that precision is twice as important as recall. FLOAT
  beta: 0.5
  #' The number of decimals to keep. INTEGER
  decimals: 4
  #' The maximal number of ions in a query. INTEGER
  max_ions: 10
  #' The minimal number of spectra per skeleton. INTEGER
  min_n_skeleton: 5
  #' The minimal number of spectra per fragment. INTEGER
  min_n_spectra: 3
  #' The minimal total intensity of the ions to keep them in the matrix. INTEGER
  min_total_intensity: 0
  #' The minimal product between sensitivity and specificity. FLOAT
  min_sensspe: 0.1
  #' The minimal sensitivity. FLOAT
  min_sensitivity: 0.3
  #' The minimal specificity. FLOAT
  min_specificity: 0

#' MS related parameters.
ms:
  #' Thresholds related parameters.
  thresholds:
    #' MS2 related parameters.
    ms2:
      #' Intensity threshold for MS2. INTEGER
      intensity: 0
  #' Tolerances.
  tolerances:
    #' For mass.
    mass:
      #' Absolute mass tolerance for MS2 in Dalton. FLOAT
      dalton: 0.01
      #' Relative mass tolerance for MS2 in ppm. FLOAT
      ppm: 25
